export const SCRIPT_UNCAUGHT_ERR = "SCRIPT_UNCAUGHT_ERR"
export const ASSETS_LOAD_FAIL = "ASSETS_LOAD_FAIL"
export const XHR_RESPONSE_ERR = "XHR_RESPONSE_ERR"

export const ASSETS_LOAD_SLOW = "ASSETS_LOAD_SLOW"
